# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artist_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ArtistMessage" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :genre, :string, 3
    optional :bio, :string, 4
  end
end

ArtistMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("ArtistMessage").msgclass
