# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: venue_message.proto

require 'google/protobuf'

require 'artist_message_pb'
require 'location_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "VenueMessage" do
    optional :id, :int32, 1
    optional :artist, :message, 2, "ArtistMessage"
    optional :location, :message, 3, "LocationMessage"
    optional :venue_date, :string, 4
  end
end

VenueMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("VenueMessage").msgclass
